### PR TITLE
Remove static variables so that VFlibTurboHandler can be used in a threa...

### PR DESCRIPTION
**Pull request by yapchunwei**
Remove static variables so that VFlibTurboHandler can be used in a threaded environment.

### CODE REVIEW

**Comment by egonw** [comment]
@johnmay did you get around to looking at this patch?

**Comment by johnmay** [comment]
I can't check this out or apply it at all so redone it. Otherwise okay but DeArom tool is legacy now (moved there now)

**Comment by egonw** [comment]
Why can't you check out these patches?

**Comment by johnmay** [comment]
"This pull request contains merge conflicts that must be resolved.
Only those with write access to this repository can merge pull requests."

**Comment by johnmay** [comment]
I can't do anything because it's on your repo.

**Comment by egonw** [comment]
True, but if you do a git fetch on my repository, doesn't that also give these patches?

If not, another trick is to click the commit link above, and add ".patch" at the end, e.g. to get:

https://github.com/yapchunwei/cdk/commit/dfac266f0541342ee8a195ecec8138f2ce09cd89.patch

(It's not that redoing is not OK, I was just hoping to get it work anyway :)

(of course, closing of this pull request probably won't work... I will try to figure out how to move these pull requests to cdk/cdk...)

**Comment by johnmay** [comment]
> True, but if you do a git fetch on my repository, doesn't that also give these patches?
Nope - thinking about it now though I could get them from  yapchunwei. Will pull from him there.

**Comment by egonw** [comment]
Ah, yes, that makes a lot of sense! should have thought of that...

**Comment by egonw** [comment]
Applied and pushed.

**Pull request closed without merging**
