### PR TITLE
Remove static keywords from variables source and target so that this cla...

### PR DESCRIPTION
**Pull request by yapchunwei**
Remove static keywords from variables source and target so that this class can be used in a threaded environment.

### CODE REVIEW

**Comment by egonw** [comment]
@johnmay did you get around to looking at this patch?

**Comment by johnmay** [comment]
No sorry I missed it... looks okay will apply and push these two now.

**Comment by johnmay** [comment]
Same as other one I can't check this out or apply it at all so redone it. We need to bug github to orphan cdk/cdk again...

**Comment by egonw** [comment]
Applied and pushed.

**Pull request closed without merging**
